/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registro.java
 *
 * Created on Nov 24, 2016, 2:37:02 PM
 */

package ventanas;

/**
 *
 * @author eddygrullon
 */
public class Registro extends javax.swing.JFrame {

    /** Creates new form Registro */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombres = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrestext = new javax.swing.JTextField();
        Apellidotext = new javax.swing.JTextField();
        emailtext = new javax.swing.JTextField();
        usuariotext = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        contraa2 = new javax.swing.JPasswordField();
        savetext = new javax.swing.JButton();
        backtext = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombres.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        nombres.setText("Nombres:");
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        Apellidos.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        Apellidos.setText("Apellidos:");
        getContentPane().add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Email.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        Email.setText("E-mail:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel3.setText("Confirmar contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        nombrestext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrestextActionPerformed(evt);
            }
        });
        getContentPane().add(nombrestext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 340, -1));

        Apellidotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidotextActionPerformed(evt);
            }
        });
        getContentPane().add(Apellidotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 340, -1));

        emailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextActionPerformed(evt);
            }
        });
        getContentPane().add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 340, -1));

        usuariotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariotextActionPerformed(evt);
            }
        });
        getContentPane().add(usuariotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 270, -1));

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });
        getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 320, -1));
        getContentPane().add(contraa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, -1));

        savetext.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        savetext.setText("Save");
        getContentPane().add(savetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        backtext.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        backtext.setText("Back");
        getContentPane().add(backtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        exit.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondito.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 530, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void usuariotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariotextActionPerformed

    private void emailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextActionPerformed

    private void ApellidotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidotextActionPerformed

    private void nombrestextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrestextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrestextActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JTextField Apellidotext;
    private javax.swing.JLabel Email;
    private javax.swing.JButton backtext;
    private javax.swing.JPasswordField contra;
    private javax.swing.JPasswordField contraa2;
    private javax.swing.JTextField emailtext;
    private javax.swing.JButton exit;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nombres;
    private javax.swing.JTextField nombrestext;
    private javax.swing.JButton savetext;
    private javax.swing.JTextField usuariotext;
    // End of variables declaration//GEN-END:variables

}
